"""
MemoryVault Agent Tools

These functions expose existing MemoryVault capabilities
to the AI Agent.

The Agent should use these tools instead of directly
accessing the database or RAG internals.
"""

import ast
import operator

import database.db as db

from rag.memory_retriever import retrieve_memories


# ==================================================
# TOOL 1 — SEARCH MEMORIES
# ==================================================

def search_memory(
    query: str,
    search_scope: str = "All Memories",
    current_document_id: int | None = None,
    selected_document_ids: list[int] | None = None,
):
    """
    Search MemoryVault memories.

    Parameters
    ----------
    query:
        Search query generated by the Agent.

    search_scope:
        One of:
            - Current Memory
            - Selected Memories
            - All Memories

    current_document_id:
        Currently selected document.

    selected_document_ids:
        Documents selected by the user.
    """

    # ==================================================
    # CURRENT MEMORY
    # ==================================================

    if search_scope == "Current Memory":

        if current_document_id is None:

            return {
                "success": False,
                "message": (
                    "No current memory is selected."
                ),
                "results": [],
            }

        document_ids = [
            current_document_id
        ]

    # ==================================================
    # SELECTED MEMORIES
    # ==================================================

    elif search_scope == "Selected Memories":

        if not selected_document_ids:

            return {
                "success": False,
                "message": (
                    "No memories were selected."
                ),
                "results": [],
            }

        document_ids = (
            selected_document_ids
        )

    # ==================================================
    # ALL MEMORIES
    # ==================================================

    else:

        document_ids = None

    # ==================================================
    # RUN EXISTING RAG
    # ==================================================

    from rag.memory_retriever import (
        retrieve_memories,
    )

    results = retrieve_memories(
        question=query,
        document_ids=document_ids,
        top_k=5,
    )

    # ==================================================
    # NO RESULTS
    # ==================================================

    if not results:

        return {
            "success": True,
            "message": (
                "No relevant information "
                "was found in the selected memories."
            ),
            "results": [],
        }

    # ==================================================
    # RETURN RESULTS
    # ==================================================

    return {
        "success": True,
        "results": results,
    }
# ==================================================
# TOOL 2 — LIST MEMORIES
# ==================================================

def list_memories():
    """
    List all memories stored in MemoryVault.

    This does NOT perform semantic search.
    It directly reads the document database.
    """

    documents = db.get_documents_with_metadata()

    memories = []

    for document in documents:

        document_id = document[0]
        filename = document[1]
        created_at = document[3]
        category = document[4]
        summary = document[5]
        keywords = document[6]
        language = document[7]

        memories.append(
            {
                "document_id": document_id,
                "filename": filename,
                "created_at": created_at,
                "category": category,
                "summary": summary,
                "keywords": keywords,
                "language": language,
            }
        )

    return {
        "success": True,
        "count": len(memories),
        "memories": memories,
    }


# ==================================================
# TOOL 3 — GET DOCUMENT INFO
# ==================================================

def get_document_info(
    document_id: int,
):
    """
    Get metadata for a specific memory/document.
    """

    documents = db.get_documents_with_metadata()

    for document in documents:

        if document[0] == document_id:

            return {
                "success": True,
                "document": {
                    "document_id": document[0],
                    "filename": document[1],
                    "file_path": document[2],
                    "created_at": document[3],
                    "category": document[4],
                    "summary": document[5],
                    "keywords": document[6],
                    "language": document[7],
                },
            }

    return {
        "success": False,
        "message": (
            f"No document found with ID {document_id}."
        ),
    }


# ==================================================
# SAFE CALCULATOR
# ==================================================

_ALLOWED_OPERATORS = {
    ast.Add: operator.add,
    ast.Sub: operator.sub,
    ast.Mult: operator.mul,
    ast.Div: operator.truediv,
    ast.Mod: operator.mod,
    ast.Pow: operator.pow,
    ast.USub: operator.neg,
    ast.UAdd: operator.pos,
}


def _safe_calculate_node(node):

    if isinstance(node, ast.Constant):

        if isinstance(node.value, (int, float)):

            return node.value

        raise ValueError(
            "Only numbers are allowed."
        )

    if isinstance(node, ast.UnaryOp):

        operation = _ALLOWED_OPERATORS.get(
            type(node.op)
        )

        if operation is None:

            raise ValueError(
                "Unsupported operation."
            )

        return operation(
            _safe_calculate_node(node.operand)
        )

    if isinstance(node, ast.BinOp):

        operation = _ALLOWED_OPERATORS.get(
            type(node.op)
        )

        if operation is None:

            raise ValueError(
                "Unsupported operation."
            )

        left = _safe_calculate_node(
            node.left
        )

        right = _safe_calculate_node(
            node.right
        )

        return operation(left, right)

    raise ValueError(
        "Invalid mathematical expression."
    )


def calculate(expression: str):
    """
    Safely evaluate a mathematical expression.

    Examples:

        2 + 2
        25 * 4
        (100 / 5) + 10
    """

    if not expression or not expression.strip():

        return {
            "success": False,
            "message": "Expression cannot be empty.",
        }

    try:

        tree = ast.parse(
            expression,
            mode="eval",
        )

        result = _safe_calculate_node(
            tree.body
        )

        return {
            "success": True,
            "expression": expression,
            "result": result,
        }

    except Exception as error:

        return {
            "success": False,
            "expression": expression,
            "message": str(error),
        }


# ==================================================
# DEBUG TEST
# ==================================================

if __name__ == "__main__":

    print()
    print("=" * 60)
    print("MEMORYVAULT TOOLS TEST")
    print("=" * 60)

    # ----------------------------------------------
    # List memories
    # ----------------------------------------------

    print("\n--- LIST MEMORIES ---")

    memories = list_memories()

    print(
        "Memory Count:",
        memories["count"],
    )

    for memory in memories["memories"]:

        print(
            memory["document_id"],
            "->",
            memory["filename"],
        )

    # ----------------------------------------------
    # Calculator
    # ----------------------------------------------

    print("\n--- CALCULATOR ---")

    print(
        calculate("2 + 2")
    )

    print(
        calculate("25 * 4")
    )

    # ----------------------------------------------
    # Document information
    # ----------------------------------------------

    print("\n--- DOCUMENT INFO ---")

    if memories["memories"]:

        first_document_id = (
            memories["memories"][0]["document_id"]
        )

        print(
            get_document_info(
                first_document_id
            )
        )

    print("=" * 60)